version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - plantuml
  jobs:
    post_checkout:
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml;
        then
          exit 183;
        fi
sphinx:
  configuration: docs/conf.py
python:
   install:
   - requirements: docs/requirements.txt
