---
event:
  key_expiry_check_period: 1
  message_history_depth: 20
  authentication_period: 30
  traffic_key_period: 86400
  host: localhost
  port: 21098
  pair:
    command: ipc://@event/pair/command

command:
  ssl_params:
    mode: server
    protocol: tlsv1_2
    key: test/ca-key.pem
    certificate: test/ca-cert.pem
    verify: none
    options: [all]
  max_clients: 16
  host: localhost
  port: 21098
  authentication_period: 30

authenticator:
  ssl_params:
    mode: server
    protocol: tlsv1_2
    key: test/ca-key.pem
    certificate: test/ca-cert.pem
    verify: none
    options: [all]
  host: localhost
  port: 21099
  db: mongodb://root:example@mongo

game:
  pair:
    event: ipc://@game/pair/event
    command: ipc://@game/pair/command

user:
  pair:
    client: ipc://@user/pair/client

client:
  ssl_params:
    mode: client
    protocol: any
    verify: none
    options: [all]
