---
event:
  key_expiry_check_period : 1
  message_history_depth : 20
  authentication_period : 30
  traffic_key_period : 86400
  host: localhost
  port: 21098
  itc_channel: 3

command:
  ssl_params :
      mode : server
      protocol : tlsv1_2
      key : test/ca-key.pem
      certificate : test/ca-cert.pem
      verify : none
      options : [all]
  handshake_timeout_period : 0.01
  max_clients : 16
  host: localhost
  port: 21098
  authentication_period : 30
  itc_channel: 1

authenticator:
  itc_channel: 2
  verify_url: https://localhost/server/verify
