---
server:
  ssl_params:
    mode: server
    protocol: tlsv1_2
    key: test/ca-key.pem
    certificate: test/ca-cert.pem
    verify: none
    options: [all]
  max_clients: 16
  host: localhost
  port: 21098
  authentication_period: 30
  message_history_depth: 20
  traffic_key_period: 86400
  ipc: ipc://@server

authenticator:
  ssl_params:
    mode: server
    protocol: tlsv1_2
    key: test/ca-key.pem
    certificate: test/ca-cert.pem
    verify: none
    options: [all]
  max_clients: 16
  host: localhost
  port: 21099
  timeout_period: 10
  user_authentication_period: 86400
  client_authentication_period: 300
  db: mongodb://root:example@mongo/?socketTimeoutMS=10000

client:
  ssl_params:
    mode: client
    protocol: any
    verify: none
    options: [all]
  ipc: ipc://@client
