name: Eiko
permissions:
  id-token: write
  contents: read
  checks: write
on:
  push:
  workflow_dispatch:
jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: rock-filter
        with:
          filters: |
            rock:
              - 'test/**'
              - 'src/**'
      - uses: dorny/paths-filter@v3
        id: builder-filter
        with:
          predicate-quantifier: 'every'
          filters: |
            builder:
              - '.devcontainer/**'
              - '!**/devcontainer.json'              
    outputs:
      rock: ${{ steps.rock-filter.outputs.rock }}
      builder: ${{ steps.builder-filter.outputs.builder }}
  builder:
    needs: 
      - filter  
    if: ${{ !failure() && !cancelled() && needs.filter.outputs.builder == 'true' }}      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:.devcontainer"
  rock:
    needs: 
      - builder
      - filter
    if: ${{ !failure() && !cancelled() && needs.filter.outputs.rock == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: dianakatana/eiko:builder
      options: --user vscode
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
    steps:
      - name: Prepare 1/2
        run: sudo sh -c "chown vscode $PWD" && git clone --branch $GITHUB_REF_NAME $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git .
      - name: Prepare 2/2
        run: chmod +x test/run_tests.sh && eval "$(luarocks path --bin)"
      - name: Build
        run: luarocks make --local
      - name: Test
        run: luarocks test --local
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Lua tests
          path: reports/*.xml
          reporter: java-junit
          fail-on-error: 'false'
