name: Eiko
permissions:
  id-token: write
  contents: read
  checks: write
on:
    push:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Build
              run: |
                .devcontainer/scripts/install_lua.sh
                runner/scripts/install.sh
                luarocks make --local
            - name: Test
              run: eval '$(luarocks path --bin)' && chmod +x test/run_tests.sh && luarocks test --local
            - name: Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()
              with:
                name: Lua tests
                path: reports/*.xml
                reporter: java-junit
                fail-on-error: 'false'
