name: Eiko
permissions:
  id-token: write
  contents: read
  checks: write
on:
  push:
  workflow_dispatch:
jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: rock-filter
        with:
          filters: |
            rock:
              - 'res/**'
              - 'test/**'
              - 'src/**'
              - 'eiko-scm-1.rockspec'
      - uses: dorny/paths-filter@v3
        id: windows-filter
        with:
          filters: |
            windows:
              - 'mingw-w64-ucrt-x86_64/**'              
    outputs:
      rock: ${{ steps.rock-filter.outputs.rock }}
      windows: ${{ steps.windows-filter.outputs.windows }}
  rock:
    needs:
      - filter
    if: ${{ !failure() && !cancelled() && needs.filter.outputs.rock == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: luajit
      - uses: leafo/gh-actions-luarocks@v4
      - name: Dependencies
        run: sudo apt update -y && xargs sudo apt install -y < .devcontainer/scripts/packages.txt
      - name: Build
        run: luarocks make --server rocks
      - name: Test
        run:  luarocks test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Lua tests
          path: reports/*.xml
          reporter: java-junit
  release-windows:
    needs:
      - filter
      - rock
    if: ${{ !failure() && !cancelled() && needs.filter.outputs.windows == 'true'}}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
      - name: Build
        run: mingw-w64-ucrt-x86_64/build.sh
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            eiko.zip
