name: Eiko
permissions:
  id-token: write
  contents: read
  checks: write
on:
  push:
  workflow_dispatch:
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          predicate-quantifier: 'every'
          filters: |
            src:
              - '.devcontainer/**'
              - '!**/devcontainer.json'
      - if: steps.filter.outputs.src == 'true'    
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - if: steps.filter.outputs.src == 'true'    
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - if: steps.filter.outputs.src == 'true'    
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:.devcontainer"
          tags: dianakatana/eiko:builder
  build:
    needs: 
      - builder
    runs-on: ubuntu-latest
    container:
      image: dianakatana/eiko:builder
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: work around permissions
        run: git config --global --add safe.directory /__w/eiko/eiko && chown vscode -R /__w/eiko/eiko
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            src:
              - 'test/**'
              - 'src/**'
      - name: work around permissions
        run: chmod +x test/run_tests.sh && su vscode && . /etc/profile   
      - if: steps.filter.outputs.src == 'true'
        name: Build
        run: luarocks make --local
      - if: steps.filter.outputs.src == 'true'
        name: Test
        run: luarocks test --local
      - if: steps.filter.outputs.src == 'true'
        name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Lua tests
          path: reports/*.xml
          reporter: java-junit
          fail-on-error: 'false'
