name: Eiko
on:
    push:
    workflow_dispatch:
jobs:
    build:
        runs-on: eiko-devcontainer
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Build
              run: luarocks make --local
            - name: Test
              run: luarocks test
