name: Eiko
permissions:
  id-token: write
  contents: read
  checks: write
on:
  push:
  workflow_dispatch:
jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: rock-filter
        with:
          filters: |
            rock:
              - 'test/**'
              - 'src/**'           
    outputs:
      rock: ${{ steps.rock-filter.outputs.rock }}
  rock:
    needs: 
      - filter
    if: ${{ !failure() && !cancelled() && needs.filter.outputs.rock == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  
      - name: Install dependencies
        run: .devcontainer/scripts/install_lua.sh
      - name: Build
        run: sudo luarocks make
      - name: Test
        run:  sudo luarocks test
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Lua tests
          path: reports/*.xml
          reporter: java-junit
          fail-on-error: 'false'
